# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 13d206e8fc6c87f88acfa1977e307135a2d03bd6addf8691bb5a0305d5ab9eca931a1cf0b32904e863d9442a068602d76310f65561492a78800ed55280568b70

test:
  secret_key_base: d096ca4ed4f652a9ae53a882b46b4089a745aded9c80a88358ad0d92d42cf3e32d8a79684aaa0c2b3d4809e7b5a7c98b584090d2c6a4005af02844d2412dc2d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
